name: Remove PSD Files

on:
  push:
    branches:
      - main

jobs:
  remove-psd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Необходимо для полной истории

      - name: Remove PSD files
        run: |
          find . -name "*.psd" -print0 | xargs -0 git rm -f --
          # Альтернатива с использованием find -exec:
          # find . -name "*.psd" -exec git rm -f {} \;

      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -m "Remove PSD files"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}